dataSource:
    driverClassName: com.mysql.cj.jdbc.Driver
    dbCreate: update
    username: root
    password: ''

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: "jdbc:mysql://localhost/mk?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"